# Generated by Django 2.2.16 on 2022-10-09 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211114_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022, 'Нельзя добавлять произведения, которые еще не вышли!')], verbose_name='Год выпуска'),
        ),
    ]
